# Generated by Django 4.0.5 on 2022-06-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('hacked_date', models.DateField(verbose_name='Hacked Date')),
                ('hacked_time', models.TimeField(verbose_name='Hacked Time')),
            ],
        ),
    ]
