# Generated by Django 4.0.5 on 2022-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_hackeddata_hacked_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackeddata',
            name='hacked_date',
            field=models.CharField(max_length=100, verbose_name='Hacked Date'),
        ),
        migrations.AlterField(
            model_name='hackeddata',
            name='hacked_time',
            field=models.CharField(max_length=100, verbose_name='Hacked Time'),
        ),
    ]
